from .consultant import ConsultantDashboardView
from .consultant import ConsultantListBoardView
from .contract import ContractListBoardView
from .employee import AppraisalListBoardView
from .employee import DashboardView
from .employee import EmployeeListBoardView
from .employee import EmployeeUpdateView
from .home_view import HomeView
from .pi import PiDashboardView
from .pi import PiListBoardView
from .reports_view import ReportsView
